# Generated by Django 5.0.1 on 2024-01-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='nombre',
        ),
    ]
