# Generated by Django 5.0.1 on 2024-01-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ap_paterno',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contra',
            new_name='password',
        ),
    ]
