# Generated by Django 5.0.1 on 2024-01-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_groups_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fec_nac',
            field=models.DateField(null=True),
        ),
    ]
