# Generated by Django 5.0.1 on 2024-01-29 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_ap_materno_alter_cliente_ciudad_and_more'),
        ('productos', '0006_remove_cliente_producto_delete_boleta_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='producto',
            field=models.ForeignKey(db_column='idproducto', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
