# Generated by Django 5.0.1 on 2024-01-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='producto',
        ),
    ]
